repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: check-case-conflict
    -   id: check-merge-conflict

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.7.0
#     hooks:
#     -   id: mypy
#         additional_dependencies:
#         - types-tqdm
#         - types-PyYAML
#         - pydantic

# -   repo: local
#     hooks:
#     -   id: pytest
#         name: pytest
#         entry: pytest
#         language: system
#         pass_filenames: false
#         always_run: true
