version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.0
    container_name: mlflow_server
    ports:
      - "${MLFLOW_PORT}:5000"
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    volumes:
      - ./${MLRUNS_DIR}:/mlruns
      - ./mlflow.db:/mlflow.db
    command: mlflow server --host 0.0.0.0 --serve-artifacts
    networks:
      - ml_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  tensorboard:
    image: tensorflow/tensorflow:2.14.0
    container_name: tensorboard_server
    ports:
      - "${TENSORBOARD_PORT}:6006"
    volumes:
      - ./${RUNS_DIR}:/runs
    command: tensorboard --logdir /runs --bind_all
    networks:
      - ml_network
    depends_on:
      mlflow:
        condition: service_healthy

networks:
  ml_network:
    name: ml_network
    driver: bridge

volumes:
  mlruns:
  runs:
